### PR TITLE
Extract library from bespin

### PR DESCRIPTION
**Pull request by johnbradley**
Library to help fix https://github.com/Duke-GCB/D4S2/issues/101

Most of the changes here are to remove unused parts of bespin-api.
Imported from bespin-api so we can maintain history.

### CODE REVIEW

**Comment by johnbradley** [comment]
TODO: 
- nail down exactly what we want to call this project
- circleci changes to publish on pypi

**Comment by johnbradley** [comment]
__bespin-api__ branch installing this library from github: https://github.com/Duke-GCB/bespin-api/tree/use-json-api-lib

**Comment by dleehr** [comment]
I appreciate the effort to preserve history (especially since I didn't do that when copying-and-pasting many of these files into D4S2). Is there a reason you didn't split these files via a [subtree](https://lostechies.com/johnteague/2014/04/04/using-git-subtrees-to-split-a-repository/)? Having the entire history of bespin-api in this repo makes it hard to trace through if that's the goal.

**Comment by dleehr** [comment]
The other part of the story is how to record that we're deleting code from bespin-api, and splitting a subtree helps there too. One hurdle with this particular change is that the files we want to split out are co-mingled in the `data` directory with lots of other bespin-api files that shouldn't be split.

While you can move the files to be split to a new subdirectory, their previous history doesn't get carried forward in the subtree: https://stackoverflow.com/questions/42661978/preserve-history-of-file-from-before-it-was-moved-into-the-directory-being-split.

**Comment by johnbradley** [comment]
Due to how this repository was created it contains 4 bogus releases and the commit history is rather ugly with all the bespin-api files we do not care about. Closing and moving to a drf-ember-backend project.

**Pull request closed without merging**
